appname:    "Rest Assured"
charset:    "UTF-8"

template:   template_toolkit
layout:     simple.tt

plugins:
    DBIC:
        default:
            dsn: dbi:SQLite:dbname=../etc/MyData.sqlite
            schema_class: MyData::Schema
